### ISSUE TITLE
SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by rytikovroman1994** [blencorp/react-lighthouse-viewer#3]
The component does not work. What the conflict in work with styles. Do you know how to solve it?

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/kodix/Documents/lighthhause-git/light-house/node_modules/react-lighthouse-viewer/dist/index.js:33:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)

**Comment by naodya** [comment]
@rytikovroman1994 you probably used a Lighhouse 5 output which is not supported yet. I'll fix this ASAP. Pull requests are always welcome. :)

**Comment by naodya** [comment]
@rytikovroman1994, please try the new version. We now support Lighthouse 5.
